### ISSUE TITLE
Start with plugin

### ISSUE THREAD

**Issue by AlexMeier99** [lektor/lektor-markdown-header-anchors#3]
I have installed the plugin via windows command line, integrated the Lines:

<h4>Table Of Contents</h4>

<ul class="toc">
{% for item in this.body.toc recursive %}
  <li><a href="#{{ item.anchor }}">{{ item.title }}</a>{%
   if item.children %}<ul>{{ loop(item.children) }}</ul>{% endif %}
{% endfor %}
</ul>

in my Template and builded the Project. Lektor builde the project without showing any errors but the ul "toc" is still empty.
What should i do now?

**Comment by niijv** [comment]
Do you have any markdown content that gets rendered on the page where you use the template?
If you copied the lines like that you would need a markdown field called "body" that has some headers (`### Headline`) in it.

Have a look atat https://www.getlektor.com/docs/what/
The "This page" section is created with the plugin, it takes its information from [this markdown content](https://github.com/lektor/lektor-website/blob/master/content/docs/what/contents.lr)

**Comment by AlexMeier99** [comment]
Ok that works... Thank you verry much!
